### ISSUE TITLE
Love the concept! But its a bit confusing

### ISSUE THREAD

**Issue by cerealconjugo** [fzzyhmstrs/piu#1]
how the mod handles backpacks concept it's one of my favorites, really! Great work.

I have play with it a little bit, and it's a bit confusing how things need to be crafted, it's more of a consistency problem with the item models, for exp: To craft a Lunchpack you need to upgrade an Large backpack, and that's seems fair, but the problem it's that instead of get a lunchpack with a design of an upgraded Large backpack, it looks like a normal Backpack with an apple inside instead... when naturally I thought it will look like an Large backpack but with an apple inside.

The sprites and the mechanics are great! It looks beautiful and feel fresh. I really love them, but it's a bit confusing,and trying to figure out how it work's without any kind of recipe viewer or seeing the wiki can bee overwhelming.

Sorry if my English it's confusing, pretty basic knowledge.

Great work and I'm excited to see how your mod grows!

**Comment by fzzyhmstrs** [comment]
Thank you for the feedback! I can see what you mean. Since these packs are "less powerful" than something like a tool backpack, I decided to make the final recipe easier and the color to match the final recipe. But maybe this isn't the right approach.

So an alternative I could do is change their textures to an "iron" color (I already have these textures actually), and have them directly craft from the simple pack (with blocks of iron in the recipe instead of just cloth)

So it would be:
Backpack > Plantpack, Lunchpack, or Large Backpack

And then higher tier packs from Large Backpack as it is. If you want to switch plantpack or lunchpack to another, you first have to switch it to Large Backpack then to the next tier.

What do you think of this?

**Comment by fzzyhmstrs** [comment]
I've gone ahead with this idea. The iron coloring makes it clear they are below the advanced golden tier but not basic cloth pack.

**Comment by cerealconjugo** [comment]
its way better!!! ease to understant an more consistent. Thanks and great work!
