### ISSUE TITLE
[Bug] Orepacks dont seem to work properly

### ISSUE THREAD

**Issue by CaviarTheCatgirl** [fzzyhmstrs/piu#2]
Crafted myself an Ore Pack and neither Coal or Raw Ore of any sort can fit into it (which I think both should as id consider both Ores, considering Lapis Lazuli, Redstone and Diamonds also fit)

**Comment by fzzyhmstrs** [comment]
Thank you for reporting this! I will take a look. And yes, it is intended to have raw ores, ore blocks, coal, redstone etc. anything that would directly drop from mining ores, be able to fit into it.

**Comment by fzzyhmstrs** [comment]
Issue fixed in version 0.1.3. Note that this checking is tag-based, so if some mod doesn't add to a tag, or adds an ore I don't know about, it won't go in unless they add to the proper tags. All vanilla ore items should work, and most mainstream mods that add raw ores. I'll continue expanding support as I find need for it.
