### ISSUE TITLE
[Suggestion] Config Option for Chestplate Slot Only

### ISSUE THREAD

**Issue by emoace** [fzzyhmstrs/piu#3]
I love the idea of this mod and think it is a great way to solve the inventory problem in Minecraft!

I know some Backpack mods have a an option to only allow backpacks to be accessed on-the-go if they are equipped to either a backpack slot or the Chestplate slot, it doesn't seem there's many of these type of backpack mods on the Fabric/Quilt ecosystem.  Something kinda like [Backpacked](https://www.curseforge.com/minecraft/mc-mods/backpacked) by Mr. Crayfish or [Shulker Box Slot](https://www.curseforge.com/minecraft/mc-mods/shulker-box-slot-fabric).

**Comment by fzzyhmstrs** [comment]
Thanks for the suggestion! I will certainly consider this as a possible addition in the future. If I were to implement it, I would probably do it as a chestplate item. I personally find trinket-based backpacks a little OP, as they can be tucked away in an "extra" slot. This also opens up the option of making a line of "armored" backpacks!

BTW, Mr. Crayfish has really amped up Backpacked since the last time I looked at it!

**Comment by emoace** [comment]
Ooooooo I like that idea! Armored Backpacks sounds really unique and thanks for responding!

**Comment by fzzyhmstrs** [comment]
Version 0.2.0 adds my first go at armorpacks! I've also added a keybind to open them without having to unequip etc ("b", surprise surprise)
